### ISSUE TITLE
DVR 18.6: USD.plugin needs "libXt" library

### ISSUE THREAD

**Issue by CityAplons** [fat-tire/resolve#42]
I have found that `libXt.so.6` is missing for the new DaVinci Resolve 18.6. 
Is it possible to add package `libXt-1.1.5-12.el8.x86_64.rpm` to the dnf installation step? What are the general rules for contribution?

![image](https://github.com/fat-tire/resolve/assets/4814678/09fe90ef-00e1-4588-a815-7b0d14cd0de9)

Also, it would be nice to append in the troubleshooting part a reference to [the NVIDIA article](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html) about installing and tweaking their container toolkit. I mentioned it primarily because of the issue with [NVML: Insufficient Permissions and SELinux](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/troubleshooting.html#nvml-insufficient-permissions-and-selinux)

Thank you for a good project and descriptive readme. Best regards,
NM

**Comment by fat-tire** [comment]
Thanks for this report and the kind words.

What are you using as your base OS-- that is, have you overridden `RESOLVE_BASE_CONTAINER_IMAGE` to use something other than the default Rocky Linux 8.x?

I ask because it looks like LibXt was installed into my container, which uses the default settings for most things.  Here's how I checked.  First, I started the container with `./resolve.sh /bin/bash` .  Then I looked to see if libXt is installed.

     bash-4.4$ dnf list installed | grep libXt
     libXt.x86_64                          1.1.5-12.el8                            @appstream 
     libXtst.x86_64                        1.2.3-7.el8                             @appstream 

So it's there.  I'm not sure why libXt isn't showing up for you.  FWIW, [libXtst is explicitly installed](https://github.com/fat-tire/resolve/blob/fceeb063f776cc4ad27adbaa77984753c41c71a4/Dockerfile#L42).  But if you think it's a good idea to add `libXt` to that line as well to make sure it's there, please try adding it  (don't forget to test it!) and if it works, submit as a pull request.  I don't mind having it added if for some distributions or even rare situations it doesn't show up.

Ditto re the reference/link to the nvidia article!  If you found something helpful in the article that you think might be useful to other people, especially for troubleshooting, create a separate pull request!  Please try to make the prose in the `README.md` as clear and readable to a non-technical audience as you think you can get away with :)

Again, thanks for trying this and helping to make the project better!

**Comment by fat-tire** [comment]
No response, so for fun I tried adding `libXt` to the build and didn't have any issues with Rocky Linux 8.6 as a base, so I'm going to just explicitly add it with a manual edit and submit as PR #43

Does this work/fix the issue for you?  Thanks!

**Comment by fat-tire** [comment]
Nothing new here in 3 weeks so I'm gonna close this.  Hopefully adding `libXt` will work for everyone.  Issues?  Feel free to re-open.
